enabled: true
pull_request: true
restylers_version: stable
exclude:
  -"**/node_modules/**/*"
  -"**/*.iml"
  -"**/.idea/**/*"
  -"**/.vsc/**/*"
restylers:
  - prettier:
      include:
        - "**/*.js"

